// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;
[TestFixture]
public class UnosenjekodakuponaTest {
  private IWebDriver driver;
  private WebDriverWait wait;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
    wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void unosenjekodakupona() {
    driver.Navigate().GoToUrl("https://www.oreabazaar.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(784, 816);
    wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".group:nth-child(3) .h-\\[20vh\\]"))).Click();
    wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".px-4"))).Click();
    wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector("a > .mx-auto"))).Click();
    wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".bg-\\[\\#f8f8f8\\]"))).Click();
    wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".bg-\\[\\#f8f8f8\\]"))).SendKeys("123456");
    wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".px-5"))).Click();
    wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".my-4"))).Click();
  }
}
